### PR TITLE
Add webpack v4 support

### PR DESCRIPTION
**Pull request by stephencookdev**
This PR should add webpack v4 (https://github.com/stephencookdev/speed-measure-webpack-plugin/issues/9)

### CODE REVIEW

**Comment by SirWindfield** [comment]
I can test this and report back if I find any weird bevahiour

**Comment by stephencookdev** [comment]
Did some more testing and found a small issue with `HardSourceWebpackPlugin` (now fixed), but no other issues!

I'll prepare a release for this later tonight :)

**Comment by SirWindfield** [comment]
Tested it on my largest project today. Seems like everything went well.

**Comment by stephencookdev** [comment]
Nice! Thanks for the help, @SirWindfield 😄

**Comment by SirWindfield** [comment]
No problem!

**Pull request merged**
